version: "3.3"
services:
  mysql:
    image: mysql:8.0.2
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Singpower
    volumes:
      - ./database:/docker-entrypoint-initdb.d