# Run ->
#   docker-compose up --build
# Stop ->
#   docker-compose down
version: "3.3"
services:
  mysql:
    image: mysql:8.0.2
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Singpower
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  friends-query-api:
    build: ./app-query
    depends_on:
      - "mysql"
    image: local/friends-query-api:latest
    # Wait for mysql to start before starting node
    command: sh -c './utilities/wait-for-it.sh mysql:3306 -- node index.js'
    container_name: friends-query-api
    ports:
      - "8000:8000"
    environment:
      - DBHOST=mysql
      - DBUSER=root
      - DBPORT=3306
      - DBPASSWORD=Singpower
      - DBDATABASE=friendshipdb
  friends-command-api:
    build: ./app-command
    depends_on:
      - "mysql"
    image: local/friends-command-api:latest
    # Wait for mysql to start before starting node
    command: sh -c './utilities/wait-for-it.sh mysql:3306 -- node index.js'
    container_name: friends-command-api
    ports:
      - "8001:8001"
    environment:
      - DBHOST=mysql
      - DBUSER=root
      - DBPORT=3306
      - DBPASSWORD=Singpower
      - DBDATABASE=friendshipdb